config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home', to: 'home#index'
  get 'about', to: 'static_pages#about'
  get 'categories', to: 'categories#categories', as: 'categories'
  get 'brands', to: 'brands#brands', as: 'brands'
  get 'product_tpyes', to: 'product_types#product_types', as: 'product_types'
  get 'search', to: 'products#search', as: 'search'
  get 'products/:id', to: 'products#show', as: 'product'

  # define routes for the categories controller that are nested under the categories resource
  # /categories/:id/show_products
  resources :categories do
    member do
      get 'show_products'
    end
  end

  resources :brands do
    member do
      get 'show_products'
    end
  end

  resources :product_types do
    member do
      get :show_products
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products

  # validations
  validates :brand_name, presence: true, length: {maximum: 20}
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  # validations
  validates :category_name, presence: true, length: {maximum: 20}
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand, optional: true
  belongs_to :category, optional: true # optional: true allows for nil values
  belongs_to :product_type, optional: true
  has_many :product_tags
  has_many :tags, through: :product_tags

 # validations
  validates :product_name, presence: true, length: { maximum: 255 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0}
  validates :image_link, presence: true
  validates :product_link, presence: true
  validates :description, presence: true
  validates :rating, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }, presence: true

  # search method
  def self.search(term, search_option)
    if term.present?
      case search_option
      when 'product'
        where('product_name LIKE ?', "%#{term}%")
      when 'category'
        joins(:category).where('category_name LIKE ?', "%#{term}%") #:category is the association name
      when 'brand'
        joins(:brand).where('brand_name LIKE ?', "%#{term}%")#brand_name is the column name
      when 'product_type'
        joins(:product_type).where('product_type_name LIKE ?', "%#{term}%")#product_type_name is the column name

      end

    end
  end
end

app/models/product_tag.rb
class ProductTag < ApplicationRecord
  belongs_to :product
  belongs_to :tag

  # validations
  # each combination of product_id and tag_id should be unique
  # but the product_id and tag_id can be repeated respectively
  validates :product_id, uniqueness: { scope: :tag_id}
end

app/models/product_type.rb
class ProductType < ApplicationRecord
  has_many :products
  validates :name, presence: true

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :product_tags
  has_many :products, through: :product_tags

  # validations
  validates :tag_name, presence: true, length: {maximum: 25}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def brands
    @brands = Brand.page(params[:page]).per(20) # paginate 20 brands per page
  end

  def show_products
    @brand = Brand.find(params[:id])
    @products = @brand.products
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def categories
    @categories = Category.all
  end

  def show_products
    @category = Category.find(params[:id])
    @products = @category.products
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @categories = Category.all
    @brands = Brand.all
    @product_types = ProductType.all
    @recommended_products = Product.where('rating >= ? AND price > ?', 5, 0).limit(4)

  end
end

app/controllers/product_types_controller.rb
class ProductTypesController < ApplicationController
  def product_types
    @product_types = ProductType.all
  end

  def show_products
    @product_type = ProductType.find(params[:id])
    @products = @product_type.products
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def search
    @results = Product.search(params[:search], params[:search_option])#params[:search] is the search term, and params[:search_option] is the search option
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/product_types_helper.rb
module ProductTypesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/brands/brands.html.erb
<div class="container mt-4 pb-5" id="category">
  <h2>Brands</h2>
  <div class="table-responsive">
    <table class="table table-striped table-hover">
      <thead class="table">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Brand Name</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @brands.each_with_index do |brand, index| %>
          <tr>
            <td><%= (index + 1) + ((@brands.current_page - 1) * @brands.limit_value) %></td>
            <td><%= brand.brand_name %></td>
            <td>
              <%= link_to 'Show Products', show_products_brand_path(brand), class: 'btn btn-primary btn-sm' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="pagination-container d-flex justify-content-center my-4">
    <%= paginate @brands, class: 'pagination' %>
  </div>

</div>

app/views/brands/show_products.html.erb
<div class="container mt-4 pb-5" id="category">
  <h2>Brand: <%= @brand.brand_name %></h2>
  <% if @products.present? %>
    <h6>Product List: <%=@products.count%> products</h6>
    <div class="table-responsive">
      <table class="table table-striped table-hover">
        <thead class="table">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Product image</th>
            <th scope="col">Product Name</th>
            <th scope="col">Price</th>
            <th scope="col">Brand</th>
            <th scope="col">Rating</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @products.each_with_index do |product, index| %>
            <tr>
              <td><%= index + 1 %></td>
              <td>
                <div style="height: 75px; width: 75px; overflow: hidden; display: flex; justify-content: center; align-items: center;">
                  <%= image_tag product.image_link, class: "img-fluid", alt: product.product_name, style: "height: 100%; width: 100%; object-fit: cover;", onerror: "this.onerror=null;this.src='#{asset_path('placeholder.png')}'" %></td>
                </div>
              <td><%= product.product_name %></td>
              <td><%= product.price %></td>
              <td><%= product.brand&.brand_name %></td>
              <td><%= product.rating %></td>
              <td>
                <%= link_to 'View', product_path(product), class: 'btn btn-primary btn-sm' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% else %>
    <p>No products found for this category</p>
  <% end %>
</div>

app/views/categories/categories.html.erb
<div class="container mt-4 pb-5" id="category">
  <h2>Categories</h2>
  <div class="table-responsive">
    <table class="table table-striped table-hover">
      <thead class="table">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Category Name</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @categories.each_with_index do |category, index| %>
          <tr>
            <td><%= index + 1 %></td>
            <td><%= category.category_name %></td>
            <td>
              <%= link_to 'Show Products', show_products_category_path(category), class: 'btn btn-primary btn-sm ' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/categories/show_products.html.erb
<div class="container mt-4 pb-5" id="category">
  <h2>Category: <%= @category.category_name %></h2>
  <% if @products.present? %>
    <h6>Product List: <%=@products.count%> products</h6>
    <div class="table-responsive">
      <table class="table table-striped table-hover">
        <thead class="table">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Product image</th>
            <th scope="col">Product Name</th>
            <th scope="col">Price</th>
            <th scope="col">Brand</th>
            <th scope="col">Rating</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @products.each_with_index do |product, index| %>
            <tr>
              <td><%= index + 1 %></td>
              <td>
                <div style="height: 75px; width: 75px; overflow: hidden; display: flex; justify-content: center; align-items: center;">
                  <%= image_tag product.image_link, class: "img-fluid", alt: product.product_name, style: "height: 100%; width: 100%; object-fit: cover;", onerror: "this.onerror=null;this.src='#{asset_path('placeholder.png')}'" %></td>
                </div>
              <td><%= product.product_name %></td>
              <td><%= product.price %></td>
              <td><%= product.brand&.brand_name %></td>
              <td><%= product.rating %></td>
              <td>
                <%= link_to 'View', product_path(product), class: 'btn btn-primary btn-sm' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% else %>
    <p>No products found for this category</p>
  <% end %>
</div>

app/views/home/index.html.erb
<main class="container mt-4 pb-5" id="main">
  <section id="recommended-products" class="mb-5">
    <!-- Recommended Products will go here -->
    <section id="recommended-products" class="mb-5">
      <h2>Recommended Products</h2>
      <div class="row mt-3">
        <% @recommended_products.each do |product| %>
          <div class="col-md-4 col-lg-3 mb-4">
            <div class="card h-100">
              <%= image_tag product.image_link, class: "card-img-top", alt: product.product_name %>
              <div class="card-body">
                <h5 class="card-title"><%= product.product_name %></h5>
                <p class="card-text">$<%= product.price %></p>
                <p class="card-text">Rating: <%= product.rating %></p>
                <%= link_to 'View', product_path(product), class: 'btn btn-primary btn-view' %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </section>

  </section>

  <section id="categories-section" class="mb-5">
    <h2>Categories</h2>
    <div class="mt-1 d-flex justify-content-center">
        <%= link_to 'All Categories', categories_path, class: 'text-dark p-2' %>
    </div>
    <div class="row mt-3">
        <% @categories.each do |category| %>
            <div class="col-md-2 mb-3">
                <div class="p-2 bg-light d-flex justify-content-center align-items-center">
                    <%= link_to category.category_name, show_products_category_path(category), class: 'text-dark text-decoration-none' %>
                </div>
            </div>
        <% end %>
    </div>
  </section>

  <section id="brands" class="mb-5">
    <!-- Brands will go here -->
    <h2>Brands</h2>
    <div class="mt-1 d-flex justify-content-center">
        <%= link_to 'All Brands', brands_path, class: 'text-dark p-2' %>
    </div>
    <div class="row mt-3">
        <% @brands.each do |brand| %>
            <div class="col-md-2 mb-3">
                <div class="p-2 bg-light d-flex justify-content-center align-items-center">
                    <%= link_to brand.brand_name, show_products_brand_path(brand), class: 'text-dark text-decoration-none' %>
                </div>
            </div>
        <% end %>
    </div>
  </section>

  <section id="product-types">
    <!-- Product Types will go here -->
    <h2>Product Types</h2>
    <div class="mt-1 d-flex justify-content-center">
        <%= link_to 'All types', product_types_path, class: 'text-dark p-2' %>
    </div>
    <div class="row mt-3">
        <% @product_types.each do |product_type| %>
            <div class="col-md-2 mb-3">
                <div class="p-2 bg-light d-flex justify-content-center align-items-center">
                    <%= link_to product_type.product_type_name, show_products_product_type_path(product_type), class: 'text-dark text-decoration-none' %>
                </div>
            </div>
        <% end %>
    </div>
  </section>
</main>

app/views/product_types/product_types.html.erb
<div class="container mt-4 pb-5" id="category">
  <h2>Product Types</h2>
  <div class="table-responsive">
    <table class="table table-striped table-hover">
      <thead class="table">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Product type Name</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @product_types.each_with_index do |product_type, index| %>
          <tr>
            <td><%= index + 1 %></td>
            <td><%= product_type.product_type_name %></td>
            <td>
              <%= link_to 'Show Products', show_products_product_type_path(product_type), class: 'btn btn-primary btn-sm ' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/product_types/show_products.html.erb
<div class="container mt-4 pb-5" id="category">
  <h2>Product Type: <%= @product_type.product_type_name%></h2>
  <% if @products.present? %>
    <h6>Product List: <%=@products.count%> products</h6>
    <div class="table-responsive">
      <table class="table table-striped table-hover">
        <thead class="table">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Product image</th>
            <th scope="col">Product Name</th>
            <th scope="col">Price</th>
            <th scope="col">Brand</th>
            <th scope="col">Rating</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @products.each_with_index do |product, index| %>
            <tr>
              <td><%= index + 1 %></td>
              <td>
                <div style="height: 75px; width: 75px; overflow: hidden; display: flex; justify-content: center; align-items: center;">
                  <%= image_tag product.image_link, class: "img-fluid", alt: product.product_name, style: "height: 100%; width: 100%; object-fit: cover;", onerror: "this.onerror=null;this.src='#{asset_path('placeholder.png')}'" %></td>
                </div>
              <td><%= product.product_name %></td>
              <td><%= product.price %></td>
              <td><%= product.brand&.brand_name %></td>
              <td><%= product.rating %></td>
              <td>
                <%= link_to 'View', product_path(product), class: 'btn btn-primary btn-sm' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% else %>
    <p>No products found for this type.</p>
  <% end %>
</div>

app/views/products/search.html.erb
<div class="container mt-4 pb-5" id="category">
  <h1>Search Results</h1>
  <% if @results.present? %>
    <h6>Product List: <%=@results.count%> products</h6>
    <div class="table-responsive">
      <table class="table table-striped table-hover">
        <thead class="table">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Product image</th>
            <th scope="col">Product Name</th>
            <th scope="col">Price</th>
            <th scope="col">Brand</th>
            <th scope="col">Category</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @results.each_with_index do |product, index| %>
            <tr>
              <td><%= index + 1 %></td>
              <td>
                <div style="height: 15px; width: 15px; overflow: hidden; display: flex; justify-content: center; align-items: center;">
                  <%= image_tag product.image_link, class: "img-fluid", alt: product.product_name, style: "height: 100%; width: 100%; object-fit: cover;", onerror: "this.onerror=null;this.src='#{asset_path('placeholder.png')}'" %></td>
                </div>
              <td><%= product.product_name %></td>
              <td><%= product.price %></td>
              <td><%= product.brand&.brand_name %></td>
              <td><%= product.category&.category_name %></td>
              <td>
                <%= link_to 'View', product_path(product), class: 'btn btn-primary btn-sm' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% else %>
    <p>No results found.</p>
  <% end %>
</div>

app/views/products/show.html.erb
<div class="container mt-4 pb-5">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <h1 class="mb-3"><%= @product.product_name %></h1>
      <div class="card">
        <img src="<%= @product.image_link %>" class="card-img-top img-fluid" alt="<%= @product.product_name %>">
        <div class="card-body">
          <h5 class="card-title"><%= @product.product_name %></h5>
          <p class="card-text"><strong>Price:</strong> $<%= @product.price %></p>
          <p class="card-text"><strong>Rating:</strong> <%= @product.rating %></p>
          <p class="card-text"><strong>Category:</strong> <%= @product.category.present? ? @product.category.category_name : 'No Category' %></p>
          <p class="card-text"><strong>Brand:</strong> <%= @product.brand.brand_name %></p>
          <p class="card-text"><strong>Product Type:</strong> <%= @product.product_type.product_type_name %></p>
          <p class="card-text"><strong>Description:</strong> <%= @product.description %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/about.html.erb
<div class="container mt-5 pb-5">
  <h1 class="mb-3">About This Application</h1>

  <p class="mb-3">This application uses the following data sources:</p>
  <ul class="mb-4">
    <li>DataSource 1: <a href="http://makeup-api.herokuapp.com" class="text-decoration-none" alt="MakeupAPILink">MakeupAPI</a></li>
    <li>DataSource 2: Faker generated data</li>
    <!-- Add more data sources as needed -->
  </ul>

  <h5 class="mb-3">Entity-Relationship Diagram (ERD)</h5>
  <%= image_tag 'erd.png', alt: 'Entity-Relationship Diagram', class: 'img-fluid mb-4' %>
</div>