config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home', to: 'home#index'
  get 'about', to: 'static_pages#about'
  get 'categories', to: 'categories#categories', as: 'categories'
  get 'brands', to: 'brands#brands', as: 'brands'
  get 'product_tpyes', to: 'product_types#product_types', as: 'product_types'
  get 'search', to: 'products#search', as: 'search'
  get 'products/:id', to: 'products#show', as: 'product'

  # define routes for the categories controller that are nested under the categories resource
  # /categories/:id/show_products
  resources :categories do
    member do
      get 'show_products'
    end
  end

  resources :brands do
    member do
      get 'show_products'
    end
  end

  resources :product_types do
    member do
      get :show_products
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products

  # validations
  validates :brand_name, presence: true, length: {maximum: 20}
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  # validations
  validates :category_name, presence: true, length: {maximum: 20}
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand, optional: true
  belongs_to :category, optional: true # optional: true allows for nil values
  belongs_to :product_type, optional: true
  has_many :product_tags
  has_many :tags, through: :product_tags

 # validations
  validates :product_name, presence: true, length: { maximum: 255 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0}
  validates :image_link, presence: true
  validates :product_link, presence: true
  validates :description, presence: true
  validates :rating, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }, presence: true

  # search method
  def self.search(term, search_option)
    if term.present?
      case search_option
      when 'product'
        where('product_name LIKE ?', "%#{term}%")
      when 'category'
        joins(:category).where('category_name LIKE ?', "%#{term}%") #:category is the association name
      when 'brand'
        joins(:brand).where('brand_name LIKE ?', "%#{term}%")#brand_name is the column name
      when 'product_type'
        joins(:product_type).where('product_type_name LIKE ?', "%#{term}%")#product_type_name is the column name

      end

    end
  end
end

app/models/product_tag.rb
class ProductTag < ApplicationRecord
  belongs_to :product
  belongs_to :tag

  # validations
  # each combination of product_id and tag_id should be unique
  # but the product_id and tag_id can be repeated respectively
  validates :product_id, uniqueness: { scope: :tag_id}
end

app/models/product_type.rb
class ProductType < ApplicationRecord
  has_many :products
  validates :name, presence: true

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :product_tags
  has_many :products, through: :product_tags

  # validations
  validates :tag_name, presence: true, length: {maximum: 25}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def brands
    @brands = Brand.page(params[:page]).per(20) # paginate 20 brands per page
  end

  def show_products
    @brand = Brand.find(params[:id])
    @products = @brand.products
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def categories
    @categories = Category.all
  end

  def show_products
    @category = Category.find(params[:id])
    @products = @category.products
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @categories = Category.all
    @brands = Brand.all
    @product_types = ProductType.all
    @recommended_products = Product.where('rating >= ? AND price > ?', 5, 0).limit(4)

  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def search
    @results = Product.search(params[:search], params[:search_option])#params[:search] is the search term, and params[:search_option] is the search option
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/product_types_helper.rb
module ProductTypesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="text-center text-lg-start bg-light text-muted pt-5 shadow-sm">
  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-3">
      <div class="row mt-3">
        <!-- Company Info -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>Company Name
          </h6>
          <p>
            Here you can use rows and columns to organize your footer content. Lorem ipsum dolor sit amet, consectetur adipisicing elit.
          </p>
        </div>

        <!-- Quick Links -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <h6 class="text-uppercase fw-bold mb-4">
            Quick links
          </h6>
          <p>
            <a href="#!" class="text-reset">About Us</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Services</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Terms of Service</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Contact Us</a>
          </p>
        </div>

        <!-- Contact -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <h6 class="text-uppercase fw-bold mb-4">
            Contact
          </h6>
          <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            info@example.com
          </p>
          <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
          <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
        </div>
      </div>
    </div>
  </section>
  <!-- Section: Links  -->

  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2024 Copyright:
    <a class="text-reset fw-bold" href="https://yourdomain.com/">FullStackDataProject_Jiajia Yang</a>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="fixed-top" >

  <nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm">
    <div class="container-fluid"> <!-- Changed to container-fluid for full width -->
      <a class="navbar-brand" href="#">
        <%= image_tag 'logo.png', alt: 'Logo', class: 'img-fluid'%> <!-- Adjusted logo size -->
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav", >
        <ul class="navbar-nav me-auto"> <!-- me-auto to align search form to the right -->
          <li class="nav-item">
            <%= link_to 'Home', root_path, class: 'nav-link ' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Category', categories_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Brand', brands_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Product Type', product_types_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'About', about_path, class: 'nav-link' %>
          </li>
        </ul>
        <form class="d-flex" method="get" action="<%= search_path %>">
          <input class="form-control me-2" type="search" name="search" placeholder="Search products" aria-label="Search">
          <select class="form-select me-2" name="search_option">
            <option value="product">Product name</option>
            <option value="category">Category</option>
            <option value="brand">Brand</option>
            <option value="product_type">Product Type</option>
            <option value="product_tag">Product Tag</option>
          </select>
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FullStackDataProject-MakeupProducts</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <!-- Bootstrap 5 CSS CDN -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <!-- Bootstrap 5 JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>